admin_section/urls.py
from django.urls import path
from .views import *
from .commands import commands

app_name = 'admin_section'


urlpatterns = [ 
   path('admin-login/' , admin_sign_in , name="admin-login")                  ,
   path('admin-logout/', admin_logout , name="admin-logout")                  ,
   path('admin-dashboard/', admin_dashoard , name="admin-dashboard" )         ,
   path('enquiry-view/' , admin_enquiry_view , name="admin_enquiry_view")     ,  
   path('see-influencers/<int:id>' , get_influencers , name="get_influencers")     ,  
   path('youtube-channel/<str:id>' , SingleChannel , name="single_channel")     ,  
   path('insta-page/<str:id>' , SinglePageInsta , name="single_page_insta")     ,  
   path('savetop20youtubers/<str:id>' , commands.SaveTop20YT , name="mostsubscribedytchannel")     ,  
   path('save-top20-insta/' , commands.SaveTop20Insta , name="saveTopInsta")     ,  
   path('save-yt/' , commands.URLtoDataYT , name="saveyt")     ,  
   path('save-fb/' , commands.StoreFBPages , name="savefb")     ,  

   path('fetch-details' , fetch_details , name="fetch-details"),
   path('get_data' , get_data , name="get_data"),
   path('challen-view/' , challen_view , name="challen-view"),
      path('get_video' , get_video, name="get_video")


]

home/urls.py
from django.urls import path
from home.views import *
app_name = 'home'

urlpatterns =[

    path('' , home , name="home")
]

intro_moment/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',    include('account.urls' ,    namespace="account") ),
    path('',    include('admin_section.urls',  namespace="admin_section" )),
    path('',    include('client.urls' ,     namespace="client") ),
    path('',    include('home.urls' ,       namespace="home") ),
    path('',    include('influencer.urls' , namespace="influencer") ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin_section/models.py
from django.db import models

# Create your models here.

admin_section/forms.py
from django import forms
from django.contrib.auth import authenticate
from account.models import accounts



class AccountAuthenticationForm(forms.ModelForm):
    class Meta:
        model = accounts
        fields = ('email', 'password')
    
    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login")

admin_section/views.py
from email import message
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate, logout ,login 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from influencer.models import YouTube_Channels, Facebook_Page, Instagram_Page, MostSubscribedYTChannel, MostViewedYTChannel, MostFollowedInstaPages
from django.http import  JsonResponse,HttpResponse

from client.models import *
from pytube import Channel
from .functions import GetSubscribersCount, ConvertStringNumberToNumber, GetTop20YTChannels,GetAllVideos_From_YTChannel_Selenium
import instaloader
from .ChannelData import YTData,get_all_video_in_channel, getVideoComments
# Create your views here.


def admin_sign_in(request):
    print("request is ",request.POST)   
    if request.user.is_authenticated: 
        return redirect("admin_section:admin-dashboard")
    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password) 
            if user:
                if user.is_admin:
                    login(request, user)
                    return redirect("admin_section:admin-dashboard")
                else:
                    logout(request)
                    messages.info(request , "You have no access") 
                    return redirect('admin_section:admin-login')  

            else:
                messages.info(request , "Inalid Credentials") 
                return redirect('admin_section:admin-login')   
    return render(request , 'signIn/sign-in.html')



@login_required(login_url='admin_section:admin-login')
def admin_logout(request):
    logout(request)
    messages.info(request , 'You are Logout Successfully')
    return redirect('admin_section:admin-login') 



@login_required(login_url='admin_section:admin-login')
def admin_dashoard(request):
    # Top20 = GetTop20YTChannels()
    # print(Top20)
    # for top in Top20:
    #     username = top.get('Username')
    #     Subscribers = top.get('Subscribers')
    #     Uploads = top.get('Uploads')
    #     VideoViews = top.get('Video Views')
    #     Link = top.get('Link').split('/')[-1]
    #     URL = f'https://youtube.com/channel/{Link}'
    #     print(Link)
    #     MostSubscribedYTChannel.objects.create(name=username, subs=Subscribers,uploads=Uploads, url=URL, TotalViews=VideoViews)
    MostSubscribedchannels = MostSubscribedYTChannel.objects.all()
    MostViewedchannels = MostViewedYTChannel.objects.all()
    TopFollowedInstaPages = MostFollowedInstaPages.objects.all()
    context = {
        'MostSubscribedchannels':MostSubscribedchannels, 
        'MostViewedchannels':MostViewedchannels,
        'TopFollowedInstaPages':TopFollowedInstaPages
        }
    return render(request , 'dashboard/dashboard.html',context )


@login_required(login_url='admin_section:admin-login')
def admin_enquiry_view(request):
    enquiries = client_enquery.objects.all()
    print(enquiries)
    return render(request , 'dashboard/enquiry.html', {'enquiries':enquiries} )

def get_data(request):
    #fetching ifluencers for selected enquiry
    ids= request.POST.get('security_code')
    d = client_enquery.objects.filter(id=ids).first()
    id_list=[]
    if d.platform == 'youtube':
        Influencers = YouTube_Channels.objects.filter(category=d.categories)
        for i in Influencers:
            id_list.append({"id":i.id})
        return JsonResponse({"status":"success" , "data":id_list})  
    elif d.platform == 'instagram':
        Pages=[]
        Influencers = Instagram_Page.objects.filter(category=d.categories)
        for Influencer in Influencers:
            id_list.append({"id":Influencer.id})
        
        return JsonResponse({"status":"success" , "data":id_list}) 
    else:    
        return JsonResponse({"status":"failed" , "data":[]})   
    


@login_required(login_url='admin_section:admin-login')
def get_influencers(request, id):
    # fetching ifluencers for selected enquiry
    d = client_enquery.objects.filter(id=id).first()

    if d.platform == 'youtube':
        Influencers = YouTube_Channels.objects.filter(category=d.categories)
        
        return render(request , 'dashboard/influencers.html', {'influencers':Influencers ,'enquery_id':d.id } )
    else:
        Pages =[]
        return render(request , 'dashboard/influencers-insta.html',  {'enquery_id':d.id } )



def fetch_details(request):
    print(request.POST)
    ids= request.POST.get('security_code')
    rows_id = request.POST.get('rows_id')
    Channels = []
    if request.POST:
        d = client_enquery.objects.filter(id=ids).first()
        if d.platform == 'youtube':
            # filtering influencers for selected category
            Influencers = YouTube_Channels.objects.filter(category=d.categories , id=rows_id)
            for channel in Influencers:
                # fetching youtube channel subscribers
                print(channel.id)
                subsCount = channel.Subs
                print("subsCount", subsCount)
                # fetching client selected subscribers count
                SelectedSubscribersCount = d.followers
                ClientSelectSubscribersList = SelectedSubscribersCount.split(' to ')

                MinSubs = ConvertStringNumberToNumber(ClientSelectSubscribersList[0])
                MaxSubs = ConvertStringNumberToNumber(ClientSelectSubscribersList[1])

                if int(subsCount) > int(MinSubs) and int(subsCount) < int(MaxSubs):
                    c = Channel(str(channel))
                    ChannelName = channel.name
                    Username = c.channel_id
                    TotalVideos = len(get_all_video_in_channel(c.channel_id))
                    dt={                'ChannelName':ChannelName, 
                                        'TotalVideos':TotalVideos, 
                                        'URL'        :str(channel), 
                                        'Category'   :d.categories,
                                        'Username'   :Username ,
                                        'subscribe':subsCount
                                        }
                    Channels.append(dt)
                else:
                    pass

                print("channels details",Channels)
        else:
            Pages=[]
            from .functions import GetInstaPageDetails, SeliniumInit
            import re

            # uncomment below code when you use selenium scraping
            # driver = SeliniumInit()
            # cookiePath = r'C:\Users\Mr Sultan\Desktop\intromomment\admin_section\auth.pkl'

            Influencers = Instagram_Page.objects.filter(category=d.categories , id=rows_id)
            for Influencer in Influencers:
                username = Influencer.url.split('/')[-1]
                PageURL = f'https://www.instagram.com/{username}'

                # uncomment below code when you use selenium scraping
                # Number_of_Posts, Number_of_Followers = GetInstaPageDetails(username, cookiePath, driver)

                Number_of_Followers , Number_of_Posts= GetInstaPageDetails(username)

                # uncomment below code when you use selenium scraping
                # strFollowers = Number_of_Followers.split(' ')
                # followers = ConvertStringNumberToNumber(strFollowers[0])

                
                followers = ConvertStringNumberToNumber(Number_of_Followers)

                # fetching client selected followers count
                ClientSelectedFollowers = d.followers
                ClientSelectFollowersList = ClientSelectedFollowers.split(' to ')

                MinFollow = ConvertStringNumberToNumber(ClientSelectFollowersList[0])
                MaxFollow = ConvertStringNumberToNumber(ClientSelectFollowersList[1])

                if int(followers) > int(MinFollow) and int(followers) < int(MaxFollow):
                    TotalPosts = Number_of_Posts
                    Channels.append({'Username':username, 'TotalPosts':TotalPosts, 'URL':str(Influencer.url), 'Category':Influencer.category})
        
            
            # print("channels details",Channels)
        # print("channels details",Channels)
        data={
            'status': "success" ,
            'data': Channels
        }
        return  JsonResponse(data , safe=False)

@login_required(login_url='admin_section:admin-login')
def SingleChannel(request, id):
    context={
        "channel":id
    }
    return render(request , 'dashboard/single-channel-yt.html',context)

@login_required(login_url='admin_section:admin-login')
def challen_view(request):
    from pytube import Channel, YouTube
    import pafy
    import scrapetube
    from datetime import datetime
    ids=request.POST.get('security_code')
    c = Channel(f'https://www.youtube.com/channel/{ids}')
    y = YTData(ids)
    AllVideosList = get_all_video_in_channel(channelID=ids)
    AllVideosData = []
    context = {
        'ChannelURL': f'https://www.youtube.com/channel/{id}',
        'Name':y.ChannelName(),
        'SubsCount':y.SubsCount(),
        'ChannelLogo':y.ThumnailURL(),
        'ChannelLocation':y.Location(),
        # 'Videos':AllVideosData,
        'VideosCount':AllVideosList,
    }
    return JsonResponse(context)

def get_video(request):
    from pytube import Channel, YouTube
    import pafy
    import scrapetube
    from datetime import datetime

    rows_id=request.POST.get('rows_id')
    VideoLink = f"https://www.youtube.com/watch?v={rows_id}"
    # if 'youtube.com' in str(video):
    try:
        yt = YouTube(VideoLink)
        yt_pafy = pafy.new(VideoLink)
        publishDate = datetime.strptime(str(yt.publish_date), "%Y-%m-%d %H:%M:%S").strftime('%d-%m-%Y')
        try:
            CommentsCount = len(getVideoComments(rows_id))
        except:

admin_section/templates/base/admin-base.html
{% load static %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Starter</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href={% static "admin_assets/plugins/fontawesome-free/css/all.min.css" %}>
  <!-- Theme style -->
  <link rel="stylesheet" href={% static "admin_assets/assets/css/adminlte.min.css" %}>
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src={% static 'admin_assets/assets/img/user1-128x128.jpg' %}  alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <span class="brand-text font-weight-light">Intromoment</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src={% static 'admin_assets/assets/img/user2-160x160.jpg' %}  class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Admin</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
               {% url 'admin_section:admin-dashboard' as dashboard_url %}
{% url 'admin_section:admin_enquiry_view' as enquiry_view %}

          <li class="nav-item">
            <a href="{% url 'admin_section:admin-dashboard' %}" class="nav-link  {% if request.path == dashboard_url %} active{% endif %} ">
              <i class="fa fa-home nav-icon"></i>             
               <p>
                Dashboard
              </p>
            </a>
              <li class="nav-item">
                <a href="{% url 'admin_section:admin_enquiry_view' %}" class="nav-link {% if request.path == enquiry_view %}active{% endif %} ">
                  <i class="fa fa-envelope nav-icon"></i>
                  <p>All Enquiries</p>
                </a>
              </li>
          </li>
       
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
          </div><!-- /.col -->
         
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->  
    </div>
    <!-- /.content-header -->
    {% block content %}
  

    {% endblock %}
  
    
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2022 <a href="https://digitalupgrowth.com/">Digitalupgrowth.com</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src={% static "admin_assets/plugins/jquery/jquery.min.js" %}></script>
<!-- Bootstrap 4 -->
<script src={% static "admin_assets/plugins/bootstrap/js/bootstrap.bundle.min.js" %}></script>
<!-- AdminLTE App -->
<script src= {% static 'admin_assets//js/adminlte.min.j' %}></script>
</body>
</html>