home/urls.py
from django.urls import path
from home.views import *
app_name = 'home'

urlpatterns =[

    path('' , home , name="home")
]

influencer/urls.py
from django.urls import path
from influencer.views import *


app_name = 'influencer'


urlpatterns = [ 
    path('influencer-register/' , influencer_register , name="influencer-register" ) ,
    path('influencer-register-step2' , influencer_register_step2 , name="influencer-register-step2" ) ,
    path('check-email' , check_email , name="check-email" ) ,
    path('check-otp/' , check_otp , name="check-otp" ) ,
    path('login/' , login , name="login" ) ,
    path('logout', logout, name="logout"),
    path('add_youtube/', add_youtube, name="add_youtube"),
    path('profile-settings/', ProfileSettings, name="ProfileSettings"),
    path('store/', StoreInfluencer, name="StoreInfluencer"),
]

intro_moment/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',    include('account.urls' ,    namespace="account") ),
    path('',    include('admin_section.urls',  namespace="admin_section" )),
    path('',    include('client.urls' ,     namespace="client") ),
    path('',    include('home.urls' ,       namespace="home") ),
    path('',    include('influencer.urls' , namespace="influencer") ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'home/home.html')

home/templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Intromoment</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
     <!-- htmx cdn -->
     <script src="https://unpkg.com/htmx.org@1.6.0"></script>
     <!-- jquery cdn -->
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


     {% comment %} this is for select element  {% endcomment %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
   
  </head>
  <body>

    <!-- Navbar -->
    <nav class="navbar header navbar-expand-lg navbar-dark">
      <div class="container-fluid container" >
        <a class="navbar-brand" href="/"><img class="logo" src="{% static 'assets/images/logox2.png' %}" alt=""></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            
          </ul>

          <div class="d-flex" role="search">
             <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            
                 <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                         Services
                      </a>
                      <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="#">Action</a></li>
                          <li><a class="dropdown-item" href="#">Another action</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="#">Something else here</a></li>
                      </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Top List</a>
                  </li>

                    <li class="nav-item">
                      <a class="nav-link" href="#">Tools</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Blogs</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle btn btn-warning mx-3 black" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          My Account
                       </a>
                       <ul class="dropdown-menu">
                         <li><a class="dropdown-item" href="#">Notifictions</a></li>
                           <li><a class="dropdown-item" href="{% url 'influencer:ProfileSettings' %}">Profile Settings</a></li>
                           <li><hr class="dropdown-divider"></li>
                           <li><a class="dropdown-item" href={% url 'influencer:logout' %}>Logout</a></li>
                       </ul>
                   </li>
                    {% else %}
                    <a type="button" href={% url 'influencer:login' %} class="btn black mx-3 btn-warning">Login / Sign Up</a>

                    {% endif %}
          </ul>
          </div>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
  <!-- DJANGO MESSAGES -->
  {% for msg in messages %}
  <div class="alert container alert-warning alert-dismissible fade show" role="alert">
       {{msg}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
 {% endfor %} 
<!-- END MESSAGES       -->

    
{% block content %}

{% endblock content %}


    <!-- Footer -->
    <footer class="text-center text-lg-start bg-light text-muted mt-5">
      <!-- Section: Social media -->
      <section class="d-flex container justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
          <span>Get connected with us on social networks:</span>
        </div>
        <!-- Left -->
    
        <!-- Right -->
        <div>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-google"></i>
          </a>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-github"></i>
          </a>
        </div>
        <!-- Right -->
      </section>
      <!-- Section: Social media -->
    
      <!-- Section: Links  -->
      <section class="">
        <div class="container text-center text-md-start mt-5">
          <!-- Grid row -->
          <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
              <!-- Content -->
              <h6 class="text-uppercase fw-bold mb-4">
                <i class="fas fa-gem me-3"></i>Intromoment
              </h6>
              <p>
                Here you can use rows and columns to organize your footer content. Lorem ipsum
                dolor sit amet, consectetur adipisicing elit.
              </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">
                Products
              </h6>
              <p>
                <a href="#!" class="text-reset">Angular</a>
              </p>
              <p>
                <a href="#!" class="text-reset">React</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Vue</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Laravel</a>
              </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">
                Useful links
              </h6>
              <p>
                <a href="#!" class="text-reset">Pricing</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Settings</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Orders</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Help</a>
              </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
              <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
              <p>
                <i class="fas fa-envelope me-3"></i>
                info@example.com
              </p>
              <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
              <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row -->
        </div>
      </section>
      <!-- Section: Links  -->
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="digitalgrowth.com">digitalgrowth</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
  <script src={% static 'assets/js/script.js' %}></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>