admin_section/urls.py
from django.urls import path
from .views import *
from .commands import commands

app_name = 'admin_section'


urlpatterns = [ 
   path('admin-login/' , admin_sign_in , name="admin-login")                  ,
   path('admin-logout/', admin_logout , name="admin-logout")                  ,
   path('admin-dashboard/', admin_dashoard , name="admin-dashboard" )         ,
   path('enquiry-view/' , admin_enquiry_view , name="admin_enquiry_view")     ,  
   path('see-influencers/<int:id>' , get_influencers , name="get_influencers")     ,  
   path('youtube-channel/<str:id>' , SingleChannel , name="single_channel")     ,  
   path('insta-page/<str:id>' , SinglePageInsta , name="single_page_insta")     ,  
   path('savetop20youtubers/<str:id>' , commands.SaveTop20YT , name="mostsubscribedytchannel")     ,  
   path('save-top20-insta/' , commands.SaveTop20Insta , name="saveTopInsta")     ,  
   path('save-yt/' , commands.URLtoDataYT , name="saveyt")     ,  
   path('save-fb/' , commands.StoreFBPages , name="savefb")     ,  

   path('fetch-details' , fetch_details , name="fetch-details"),
   path('get_data' , get_data , name="get_data"),
   path('challen-view/' , challen_view , name="challen-view"),
      path('get_video' , get_video, name="get_video")


]

home/urls.py
from django.urls import path
from home.views import *
app_name = 'home'

urlpatterns =[

    path('' , home , name="home")
]

influencer/urls.py
from django.urls import path
from influencer.views import *


app_name = 'influencer'


urlpatterns = [ 
    path('influencer-register/' , influencer_register , name="influencer-register" ) ,
    path('influencer-register-step2' , influencer_register_step2 , name="influencer-register-step2" ) ,
    path('check-email' , check_email , name="check-email" ) ,
    path('check-otp/' , check_otp , name="check-otp" ) ,
    path('login/' , login , name="login" ) ,
    path('logout', logout, name="logout"),
    path('add_youtube/', add_youtube, name="add_youtube"),
    path('profile-settings/', ProfileSettings, name="ProfileSettings"),
    path('store/', StoreInfluencer, name="StoreInfluencer"),
]

intro_moment/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',    include('account.urls' ,    namespace="account") ),
    path('',    include('admin_section.urls',  namespace="admin_section" )),
    path('',    include('client.urls' ,     namespace="client") ),
    path('',    include('home.urls' ,       namespace="home") ),
    path('',    include('influencer.urls' , namespace="influencer") ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin_section/models.py
from django.db import models

# Create your models here.

admin_section/forms.py
from django import forms
from django.contrib.auth import authenticate
from account.models import accounts



class AccountAuthenticationForm(forms.ModelForm):
    class Meta:
        model = accounts
        fields = ('email', 'password')
    
    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login")

influencer/forms.py
from django import forms
from .models import YouTube_Channels

class YouTube_Channel_Form(forms.ModelForm):
    body = forms.CharField(required=True)

    class Meta:
        model = YouTube_Channels
        exclude = ("user", )

admin_section/views.py
from email import message
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate, logout ,login 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from influencer.models import YouTube_Channels, Facebook_Page, Instagram_Page, MostSubscribedYTChannel, MostViewedYTChannel, MostFollowedInstaPages
from django.http import  JsonResponse,HttpResponse

from client.models import *
from pytube import Channel
from .functions import GetSubscribersCount, ConvertStringNumberToNumber, GetTop20YTChannels,GetAllVideos_From_YTChannel_Selenium
import instaloader
from .ChannelData import YTData,get_all_video_in_channel, getVideoComments
# Create your views here.


def admin_sign_in(request):
    print("request is ",request.POST)   
    if request.user.is_authenticated: 
        return redirect("admin_section:admin-dashboard")
    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password) 
            if user:
                if user.is_admin:
                    login(request, user)
                    return redirect("admin_section:admin-dashboard")
                else:
                    logout(request)
                    messages.info(request , "You have no access") 
                    return redirect('admin_section:admin-login')  

            else:
                messages.info(request , "Inalid Credentials") 
                return redirect('admin_section:admin-login')   
    return render(request , 'signIn/sign-in.html')



@login_required(login_url='admin_section:admin-login')
def admin_logout(request):
    logout(request)
    messages.info(request , 'You are Logout Successfully')
    return redirect('admin_section:admin-login') 



@login_required(login_url='admin_section:admin-login')
def admin_dashoard(request):
    # Top20 = GetTop20YTChannels()
    # print(Top20)
    # for top in Top20:
    #     username = top.get('Username')
    #     Subscribers = top.get('Subscribers')
    #     Uploads = top.get('Uploads')
    #     VideoViews = top.get('Video Views')
    #     Link = top.get('Link').split('/')[-1]
    #     URL = f'https://youtube.com/channel/{Link}'
    #     print(Link)
    #     MostSubscribedYTChannel.objects.create(name=username, subs=Subscribers,uploads=Uploads, url=URL, TotalViews=VideoViews)
    MostSubscribedchannels = MostSubscribedYTChannel.objects.all()
    MostViewedchannels = MostViewedYTChannel.objects.all()
    TopFollowedInstaPages = MostFollowedInstaPages.objects.all()
    context = {
        'MostSubscribedchannels':MostSubscribedchannels, 
        'MostViewedchannels':MostViewedchannels,
        'TopFollowedInstaPages':TopFollowedInstaPages
        }
    return render(request , 'dashboard/dashboard.html',context )


@login_required(login_url='admin_section:admin-login')
def admin_enquiry_view(request):
    enquiries = client_enquery.objects.all()
    print(enquiries)
    return render(request , 'dashboard/enquiry.html', {'enquiries':enquiries} )

def get_data(request):
    #fetching ifluencers for selected enquiry
    ids= request.POST.get('security_code')
    d = client_enquery.objects.filter(id=ids).first()
    id_list=[]
    if d.platform == 'youtube':
        Influencers = YouTube_Channels.objects.filter(category=d.categories)
        for i in Influencers:
            id_list.append({"id":i.id})
        return JsonResponse({"status":"success" , "data":id_list})  
    elif d.platform == 'instagram':
        Pages=[]
        Influencers = Instagram_Page.objects.filter(category=d.categories)
        for Influencer in Influencers:
            id_list.append({"id":Influencer.id})
        
        return JsonResponse({"status":"success" , "data":id_list}) 
    else:    
        return JsonResponse({"status":"failed" , "data":[]})   
    


@login_required(login_url='admin_section:admin-login')
def get_influencers(request, id):
    # fetching ifluencers for selected enquiry
    d = client_enquery.objects.filter(id=id).first()

    if d.platform == 'youtube':
        Influencers = YouTube_Channels.objects.filter(category=d.categories)
        
        return render(request , 'dashboard/influencers.html', {'influencers':Influencers ,'enquery_id':d.id } )
    else:
        Pages =[]
        return render(request , 'dashboard/influencers-insta.html',  {'enquery_id':d.id } )



def fetch_details(request):
    print(request.POST)
    ids= request.POST.get('security_code')
    rows_id = request.POST.get('rows_id')
    Channels = []
    if request.POST:
        d = client_enquery.objects.filter(id=ids).first()
        if d.platform == 'youtube':
            # filtering influencers for selected category
            Influencers = YouTube_Channels.objects.filter(category=d.categories , id=rows_id)
            for channel in Influencers:
                # fetching youtube channel subscribers
                print(channel.id)
                subsCount = channel.Subs
                print("subsCount", subsCount)
                # fetching client selected subscribers count
                SelectedSubscribersCount = d.followers
                ClientSelectSubscribersList = SelectedSubscribersCount.split(' to ')

                MinSubs = ConvertStringNumberToNumber(ClientSelectSubscribersList[0])
                MaxSubs = ConvertStringNumberToNumber(ClientSelectSubscribersList[1])

                if int(subsCount) > int(MinSubs) and int(subsCount) < int(MaxSubs):
                    c = Channel(str(channel))
                    ChannelName = channel.name
                    Username = c.channel_id
                    TotalVideos = len(get_all_video_in_channel(c.channel_id))
                    dt={                'ChannelName':ChannelName, 
                                        'TotalVideos':TotalVideos, 
                                        'URL'        :str(channel), 
                                        'Category'   :d.categories,
                                        'Username'   :Username ,
                                        'subscribe':subsCount
                                        }
                    Channels.append(dt)
                else:
                    pass

                print("channels details",Channels)
        else:
            Pages=[]
            from .functions import GetInstaPageDetails, SeliniumInit
            import re

            # uncomment below code when you use selenium scraping
            # driver = SeliniumInit()
            # cookiePath = r'C:\Users\Mr Sultan\Desktop\intromomment\admin_section\auth.pkl'

            Influencers = Instagram_Page.objects.filter(category=d.categories , id=rows_id)
            for Influencer in Influencers:
                username = Influencer.url.split('/')[-1]
                PageURL = f'https://www.instagram.com/{username}'

                # uncomment below code when you use selenium scraping
                # Number_of_Posts, Number_of_Followers = GetInstaPageDetails(username, cookiePath, driver)

                Number_of_Followers , Number_of_Posts= GetInstaPageDetails(username)

                # uncomment below code when you use selenium scraping
                # strFollowers = Number_of_Followers.split(' ')
                # followers = ConvertStringNumberToNumber(strFollowers[0])

                
                followers = ConvertStringNumberToNumber(Number_of_Followers)

                # fetching client selected followers count
                ClientSelectedFollowers = d.followers
                ClientSelectFollowersList = ClientSelectedFollowers.split(' to ')

                MinFollow = ConvertStringNumberToNumber(ClientSelectFollowersList[0])
                MaxFollow = ConvertStringNumberToNumber(ClientSelectFollowersList[1])

                if int(followers) > int(MinFollow) and int(followers) < int(MaxFollow):
                    TotalPosts = Number_of_Posts
                    Channels.append({'Username':username, 'TotalPosts':TotalPosts, 'URL':str(Influencer.url), 'Category':Influencer.category})
        
            
            # print("channels details",Channels)
        # print("channels details",Channels)
        data={
            'status': "success" ,
            'data': Channels
        }
        return  JsonResponse(data , safe=False)

@login_required(login_url='admin_section:admin-login')
def SingleChannel(request, id):
    context={
        "channel":id
    }
    return render(request , 'dashboard/single-channel-yt.html',context)

@login_required(login_url='admin_section:admin-login')
def challen_view(request):
    from pytube import Channel, YouTube
    import pafy
    import scrapetube
    from datetime import datetime
    ids=request.POST.get('security_code')
    c = Channel(f'https://www.youtube.com/channel/{ids}')
    y = YTData(ids)
    AllVideosList = get_all_video_in_channel(channelID=ids)
    AllVideosData = []
    context = {
        'ChannelURL': f'https://www.youtube.com/channel/{id}',
        'Name':y.ChannelName(),
        'SubsCount':y.SubsCount(),
        'ChannelLogo':y.ThumnailURL(),
        'ChannelLocation':y.Location(),
        # 'Videos':AllVideosData,
        'VideosCount':AllVideosList,
    }
    return JsonResponse(context)

def get_video(request):
    from pytube import Channel, YouTube
    import pafy
    import scrapetube
    from datetime import datetime

    rows_id=request.POST.get('rows_id')
    VideoLink = f"https://www.youtube.com/watch?v={rows_id}"
    # if 'youtube.com' in str(video):
    try:
        yt = YouTube(VideoLink)
        yt_pafy = pafy.new(VideoLink)
        publishDate = datetime.strptime(str(yt.publish_date), "%Y-%m-%d %H:%M:%S").strftime('%d-%m-%Y')
        try:
            CommentsCount = len(getVideoComments(rows_id))
        except:

admin_section/templates/dashboard/dashboard.html
{% extends 'base/admin-base.html' %}
{% block content %}



  <div style='display:flex;' class="container ">
    <div style="background-color: rgb(243, 249, 255); border: 0.5px solid #9e9e9e; padding: 15px; border-radius: 5px;" class="col-6 m-2">
      <h4 class="text-center mb-3">Top 20 Most Subscribed YouTubers</h4>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Channel</th>
            <th scope="col">Uploads</th>
            <th scope="col">Subs</th>
          </tr>
        </thead>
        <tbody>
          {% for channel in MostSubscribedchannels %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href={{channel.url}}>{{channel.name}}</a></td>
            <td>{{channel.uploads}}</td>
            <td>{{channel.subs}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div style="background-color: rgb(243, 249, 255); border: 0.5px solid #9e9e9e; padding: 15px; border-radius: 5px;" class="col-6 m-2">
      <h4 class="text-center mb-3">Top 20 Most Viewd YouTubers</h4>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Channel</th>
            <th scope="col">Uploads</th>
            <th scope="col">Subs</th>
          </tr>
        </thead>
        <tbody>
          {% for channel_view in MostViewedchannels %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href={{channel_view.url}}>{{channel_view.name}}</a></td>
            <td>{{channel_view.uploads}}</td>
            <td>{{channel_view.subs}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

  </div>

  <div style='display:flex;' class="container my-3">
    <div style="background-color: rgb(243, 249, 255); border: 0.5px solid #9e9e9e; padding: 15px; border-radius: 5px;" class="col-6 m-2">
      <h4 class="text-center mb-3">Top 20 Most Followed Instaragram Pages</h4>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">Posts</th>
            <th scope="col">Followers</th>
          </tr>
        </thead>
        <tbody>
          {% for page in TopFollowedInstaPages %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href={{page.url}}>{{page.username}}</a></td>
            <td>{{page.posts}}</td>
            <td>{{page.followers}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>



  </div>

{% endblock %}

admin_section/templates/dashboard/influencers-insta.html
{% extends 'base/admin-base.html' %}
{% block content %}

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Suggested Influencers</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 1%">
                          #
                      </th>
                      <th style="width: 20%">
                        Page
                      </th>
                      <th style="width: 15%">
                        Number of Posts	
                      </th>
                      <th style="width: 10%"  >
                        Location
                      </th>
                    
                     
                      <th style="width: 15%">
                        
                      </th>
                  </tr>
              </thead>

              {% comment %} {% if influencers != None %} {% endcomment %}
              <tbody id="myBody">
                
                  </tbody>
                  
                </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
     <center> <button class="btn btn-primary" type="button" disabled>
        <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
        Loading...
      </button>
    </center>
    </section>
    <!-- /.content -->


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <form action="" method="POST">
    {% csrf_token %}
    <input type="hidden" name="ids" value="{{enquery_id}}">
    </form>  
      


    
<script>

  function get_data(){
    $.ajax({
            url: "{% url 'admin_section:get_data' %}",
            type: "POST",
            data: {
                security_code:$("input[name='ids']").val(),
                csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
            },
            success: function (data) {
              console.log(data)
              response = data.data
              var count=1
              for (var i = 0; i < response.length; i++){
                      // start here
                      function start_func(){ 
                                $.ajax({
                                    url: "{% url 'admin_section:fetch-details' %}",
                                    type: "POST",
                                    data: {
                                        security_code:$("input[name='ids']").val(),
                                        rows_id:response[i].id,
                                        csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
                                    }, 
                                    success: function (data) {
                                        console.log("out of loop",data);
                                        var table = document.getElementById('myBody')
                                        if(data.status == "success"){
                                          response = data.data
                                          console.log("succes",response)
                                          
                                          for (var i = 0; i < response.length; i++){
                                            var row = `<tr>
                                                  <td>${count}</td>  
                                                  <td><a  href='${response[i].URL}'>${response[i].Username}</a></td>
                                                  <td>${response[i].TotalPosts}</td>
                                                  <td> Hong Kong </td>
                                                  
                                                  <td class="project-actions text-right">
                                                      <a class="btn btn-primary btn-sm" href="/insta-page/${response[i].Username}">
                                                          <i class="fas fa-eye">
                                                          </i>
                                                          View Channel
                                                      </a>
                                                      
                                                  </td>
                                                  </tr>`
                                            table.innerHTML += row
                                            count++ ;
                                          }
                                          $('#htable').hide()     
                                        }
                                        else{
                                            alert(data.status);
                                        }
                                    }
                                });
                              }

                    // end here
                    window.addEventListener("load" , start_func())

                  }
            }
        });
  }

       
          
    window.addEventListener("load" , get_data())

</script>


    

{% endblock %}

admin_section/templates/dashboard/influencers.html
{% extends 'base/admin-base.html' %}
{% block content %}

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Suggested Influencers</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-0">


          <table class="table table-striped projects" >
            <thead>
                <tr>
                    <th style="width: 1%">
                        #
                    </th>
                    <th style="width: 20%">
                      Channel
                    </th>
                    <th style="width: 15%">
                      Number of Videos	
                    </th>
                    <th style="width: 10%"  >
                      Location
                    </th>
                    <th style="width: 10%" class="text-center">
                      Category	
                    </th>
                  
                    <th style="width: 15%">
                        Subscriber
                    </th>

                    <th style="width: 15%">
                        
                    </th>
                </tr>
            </thead>
  
  
              <tbody id="myBody">
             
               
                    
                <tr id="htable">
                  <td>
                    please wait.......
                  </td>
                 
                </tr>
                
          
              
              </tbody>
        </table>


        </div>
        
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <form action="" method="POST">
  {% csrf_token %}
  <input type="hidden" name="ids" value="{{enquery_id}}">
 
  </form>  
    




 
<script>

    function get_data(){
      $.ajax({
              url: "{% url 'admin_section:get_data' %}",
              type: "POST",
              data: {
                  security_code:$("input[name='ids']").val(),
                  csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
              },
              
              success: function (data) {
                console.log("get_data" , data)
                response = data.data
                var count = 1
                for (var j = 0; j < response.length; j++){
                        // start here
                      console.log(j)  
                      function start_func(){ 
                                $.ajax({
                                    url: "{% url 'admin_section:fetch-details' %}",
                                    type: "POST",
                                    data: {
                                        security_code:$("input[name='ids']").val(),
                                        rows_id:response[j].id,
                                        csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
                                    },
                                    
                                    success: function (data) {
                                        console.log("out of loop",data);
                                        var table = document.getElementById('myBody')
                                        if(data.status == "success"){
                                          response = data.data
                                          console.log("succes",response)
                                          
                                          for (var i = 0; i < response.length; i++){
                                          
                                          
                                          var  row =`
                                                  <tr>
                                                        <td>${count}</td>
                                                        <td><a href='${response[i].URL}'>${response[i].ChannelName}</a?</td>
                                                        <td>${response[i].TotalVideos}</td>
                                                        <td> Hong Kong </td>
                                                        <td>${response[i].Category}</td>
                                                        <td>${response[i].subscribe}</td>
                                                        <td class="project-actions text-right">
                                                          <a class="btn btn-primary btn-sm" href="/youtube-channel/${response[i].Username}">
                                                              <i class="fas fa-eye">
                                                              </i>
                                                              View Channel
                                                          </a>
                                                          
                                                        </td>
                                                        </tr>
                                                  `
                                            table.innerHTML += row
                                            count++
                                          }
                                          $('#htable').hide()     
                                        }
                                        else{
                                            alert(data.status);
                                        }
                                    }
                                });
                              }

                      // end here
                      window.addEventListener("load" , start_func())

                    }
              }
          });
    }

         
            
      window.addEventListener("load" , get_data())

</script>


{% endblock %}