home/urls.py
from django.urls import path
from home.views import *
app_name = 'home'

urlpatterns =[

    path('' , home , name="home")
]

influencer/urls.py
from django.urls import path
from influencer.views import *


app_name = 'influencer'


urlpatterns = [ 
    path('influencer-register/' , influencer_register , name="influencer-register" ) ,
    path('influencer-register-step2' , influencer_register_step2 , name="influencer-register-step2" ) ,
    path('check-email' , check_email , name="check-email" ) ,
    path('check-otp/' , check_otp , name="check-otp" ) ,
    path('login/' , login , name="login" ) ,
    path('logout', logout, name="logout"),
    path('add_youtube/', add_youtube, name="add_youtube"),
    path('profile-settings/', ProfileSettings, name="ProfileSettings"),
    path('store/', StoreInfluencer, name="StoreInfluencer"),
]

intro_moment/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',    include('account.urls' ,    namespace="account") ),
    path('',    include('admin_section.urls',  namespace="admin_section" )),
    path('',    include('client.urls' ,     namespace="client") ),
    path('',    include('home.urls' ,       namespace="home") ),
    path('',    include('influencer.urls' , namespace="influencer") ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

influencer/models.py
from django.db import models
from account.models import accounts
# Create your models here.



class influencer_profile(models.Model):
    user                = models.ForeignKey(accounts, on_delete=models.CASCADE)
    name                = models.CharField(max_length=100)
    url                 = models.URLField(max_length=200 , null=True , blank=True)
    description         = models.TextField(null=True , blank=True)
    phone               = models.CharField(max_length=20 , null=True , blank=True)
    account_name_id     = models.CharField(max_length=100 , null=True , blank=True)

    Instagram_page_url = models.URLField(blank=True, max_length=200, null=True)
    Facebook_page_url = models.URLField(blank=True, max_length=200, null=True)
    Youtube_channel_url = models.URLField(blank=True, max_length=200, null=True)
    #categories      

    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


    class Meta:
        verbose_name_plural = "Influencer Profiles"
        verbose_name        = "Influencer Profiles"


class YouTube_Channels(models.Model):
    id                  = models.AutoField(primary_key=True)
    user =              models.ForeignKey(accounts, on_delete=models.CASCADE, blank=True, null=True)
    url                 = models.URLField(max_length=2000 , null=True , blank=True)
    category            = models.CharField(max_length=200, blank=True, null=True)
    name            = models.CharField(max_length=200, blank=True, null=True)
    Subs                = models.CharField(max_length=12323232323 , blank=True, null=True)
    location            = models.CharField(max_length=200, null=True , blank=True )
    NumberofVideos      = models.IntegerField(blank=True, null=True)
    ProfilePicLink      = models.URLField(max_length=2000 , blank=True, null=True)
    AllVideos           = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.url

class Instagram_Page(models.Model):
    id                  = models.AutoField(primary_key=True)
    user =              models.ForeignKey(accounts, on_delete=models.CASCADE, blank=True, null=True)
    name                = models.CharField(max_length=200, blank=True, null=True)
    url                 = models.URLField(max_length=2000 , null=True , blank=True)
    posts               = models.TextField(blank=True, null=True)
    postsCount               = models.CharField(max_length=50000000000000000000,blank=True, null=True)
    followersCount                = models.CharField(max_length=12323232323 , blank=True, null=True)
    ProfilePicLink      = models.URLField(max_length=20000 , blank=True, null=True)
    category            = models.CharField(max_length=200, blank=True, null=True)
    location            = models.CharField(max_length=200, null=True , blank=True )

    def __str__(self):
        return self.url

class Facebook_Page(models.Model):
    id                  = models.AutoField(primary_key=True)
    user =              models.ForeignKey(accounts, on_delete=models.CASCADE, blank=True, null=True)
    name            = models.CharField(max_length=200, blank=True, null=True)
    url                 = models.URLField(max_length=2000 , null=True , blank=True)
    posts               = models.TextField(blank=True, null=True)
    postsCount               = models.CharField(max_length=50000000000000000000,blank=True, null=True)
    followersCount                = models.CharField(max_length=12323232323 , blank=True, null=True)
    ProfilePicLink      = models.URLField(max_length=20000 , blank=True, null=True)
    category            = models.CharField(max_length=200, blank=True, null=True)
    location            = models.CharField(max_length=200, null=True , blank=True )

    def __str__(self):
        return self.url

class MostSubscribedYTChannel(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    url = models.URLField(max_length=200, null=True , blank=True)
    uploads = models.CharField(max_length=200, blank=True, null=True)
    subs = models.CharField(max_length=200, blank=True, null=True)
    TotalViews = models.CharField(max_length=2020, blank=True, null=True)

    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

class MostViewedYTChannel(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    url = models.URLField(max_length=200, null=True , blank=True)
    uploads = models.CharField(max_length=200, blank=True, null=True)
    subs = models.CharField(max_length=200, blank=True, null=True)
    TotalViews = models.CharField(max_length=2020, blank=True, null=True)

    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)
    
class MostFollowedInstaPages(models.Model):
    username = models.CharField(max_length=200, blank=True, null=True)
    url = models.URLField(max_length=200, null=True , blank=True)
    posts = models.CharField(max_length=200, blank=True, null=True)
    followers = models.CharField(max_length=200, blank=True, null=True)
    engagementRate = models.CharField(max_length=2020, blank=True, null=True)

    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)

influencer/forms.py
from django import forms
from .models import YouTube_Channels

class YouTube_Channel_Form(forms.ModelForm):
    body = forms.CharField(required=True)

    class Meta:
        model = YouTube_Channels
        exclude = ("user", )

influencer/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse , JsonResponse
from account.models import accounts
from .models import *
import random
from django.contrib import messages
from django.contrib.auth import authenticate,logout as deauth, login  as dj_login
from django.conf import settings 
from django.core.mail import send_mail

from influencer.models import *
# Create your views here.

def send_otp(email , otp):
    pass


def check_email(request):
    if request.method == 'POST':
        get_email =request.POST.get('email')
        
        if accounts.objects.filter(email=get_email).exists():
            return HttpResponse(f"""
                        <div id='Msg' class='text-danger'>
                            <p>This Email Already Exist</p>
                        </div>""")
        
        
        else:
            # accounts.objects.filter(email=get_email).update(otp=random.randint(1000,9999))
            otp=random.randint(1000 , 9999)
            request.session['reg_otp'] = otp
            print("OTP",otp)
            send_mail('OTP from Intromoment Influencer Register', f'YOur OTP from Intromoment is {otp}', 't4technology09@gmail.com', recipient_list=[get_email])
            
            
            return HttpResponse(f"""
                                <div id='Msg'>
                                        <div class="form-group mt-1">
                                               <p class='text-success'>An Otp  has been sent to your email</p>
                                            </div>
                                        
                                        </div>                                        
                                        
                                        
                                        <div class="form-group mt-3">
                    
                                                <div class="">
                                                    <input  
                                                            type="text" 
                                                            name="otp" 
                                                            class="form-control"
                                                            placeholder="Enter OTP"
                                                            hx-post="/check-otp/" 
                                                            hx-target="#OTPMsg" 
                                                            hx-trigger="keyup delay:2s"
                                                    >
                                                </div>

                                                <div id="OTPMsg">

                                                </div>

                                        </div>
                                
                                </div>
                                
                                """)
                
def check_otp(request):
    if request.method == 'POST':
        get_otp =request.POST.get('otp')
        reg_otp = request.session.get('reg_otp')
        if get_otp == str(reg_otp):
            return HttpResponse(f"""
                        <div id='OTPMsg' class='text-success'>
                              <div class="form-group row mt-3">
                                            <div class="col-md-4">
                                            </div>
                                            
                                            <div class="col-md-6"> 
                                            <p class='text-success'>Otp is correct</p>
                                            </div>
                                        
                                </div>          
                        </div>""")
        
        else:
            return HttpResponse(f"""
                        <div id='OTPMsg' class='text-danger'>
                              <div class="form-group row mt-3">
                                            <div class="col-md-4">
                                            </div>
                                            
                                            <div class="col-md-6"> 
                                            <p class='text-danger'>Otp is Incorrect</p>
                                            </div>
                                        
                                </div>          
                        </div>""")

def influencer_register(request):
    if request.method == 'POST':
        get_email       = request.POST.get('email')
        get_otp         = request.POST.get('otp')
        get_password1   = request.POST.get('password1')
        get_password2   = request.POST.get('password2') 
        get_name        = request.POST.get('username')

        reg_otp = request.session.get('reg_otp')

        if not get_email:
            return JsonResponse({"status":"Enter Email"})

        if accounts.objects.filter(email=get_email).exists():
            return JsonResponse({"status":"Email Already Exist"})    

        if not  get_otp == str(reg_otp):
            return JsonResponse({"status":"Invalid OTP"})

        if not get_password1 == get_password2:
            return JsonResponse({"status":"Password Not Matched"})

        if len(get_password1) < 4:
            return JsonResponse({"status":"Password Must be 4 Character Long"})     

        
        
        get_obj=accounts.objects.create(username=get_name , email=get_email)
        get_obj.set_password(get_password1)
        get_obj.save()

        influencer_profile.objects.create(
            user = get_obj,
            name = get_name        )

        user = authenticate(email=get_email , password=get_password1)

        dj_login(request , user)
        
        return redirect('influencer:influencer-register-step2')    

    return render(request, 'register/register.html')



def influencer_register_step2(request):
    if request.method == 'POST':
        fb_url       = request.POST.get('fb_url')
        fb_category      = request.POST.get('fb_category')

        yt_url         = request.POST.get('yt_url')
        yt_category        = request.POST.get('yt_category')

        insta_url   = request.POST.get('insta_url')
        insta_category   = request.POST.get('insta_category')

        Facebook_Page.objects.create(user=request.user, url=fb_url, category=fb_category, location='Hong Kong')
        Instagram_Page.objects.create(user=request.user, url=insta_url, category=insta_category, location='Hong Kong')
        YouTube_Channels.objects.create(user=request.user, url=yt_url, category=yt_category, location='Hong Kong')

        return redirect('home:home')    

    return render(request, 'register-step-2.html')


def login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(email=email, password=password)
        try:
            dj_login(request, user)
        except ValueError:
            messages.info(request, "Check your Login Creds")
        

    return render(request, 'login/login.html')

def logout(request):
	if request.user.is_authenticated:
		deauth(request)
	messages.info(request , 'You are Logout Successfully')
	return redirect('home:home')


def add_youtube(request):
    if request.method == 'POST':
        import requests
        from bs4 import BeautifulSoup
        from termcolor import colored

        InputCategory = request.POST.get('category')

        # this is for hong kong
        # ChannelCrawlerCategories = {'Education':'876973', 'Entertainment':'980862', 'Film and Animation':'982376','Gaming':'964607','Howto & Style':'982377','Music':'982379', 'News & Politics':'982381','People & Blogs':'966857','Pets & Animals':'982385', 'Science & Technology':'928708', 'Sports':'344310','Travel & Events':'982386'}
 
        # this is for china
        # ChannelCrawlerCategories = {'Education':'415768', 'Entertainment':'318110', 'Film and Animation':'1002164','Gaming':'487346','Howto & Style':'670275','Music':'313018', 'News & Politics':'403758','People & Blogs':'296935','Pets & Animals':'501791', 'Science & Technology':'369011', 'Sports':'1006287','Travel & Events':'1028987'}

        # this is for Macau
        # ChannelCrawlerCategories = {'Education':'1029090', 'Entertainment':'1029092', 'Film and Animation':'1029093','Gaming':'1014991','Howto & Style':'1029097','Music':'1029098', 'News & Politics':'812474','People & Blogs':'1029100','Pets & Animals':'1029102', 'Science & Technology':'1029103', 'Sports':'367610','Travel & Events':'1029104'}
     
        # this is for Taiwan
        ChannelCrawlerCategories = {'Education':'750311', 'Entertainment':'722407', 'Film and Animation':'750496','Gaming':'391843','Howto & Style':'632851','Music':'1029112', 'News & Politics':'750516','People & Blogs':'678956','Pets & Animals':'1029113', 'Science & Technology':'496828', 'Sports':'1029115','Travel & Events':'1029117'}


        Category = ChannelCrawlerCategories.get(InputCategory)
        print(colored('Searching Channels for ', 'red'), colored(InputCategory, 'green'),colored('.........'))

        r= requests.get(f'https://channelcrawler.com/eng/results2/{Category}/')
        html = BeautifulSoup(r.text, 'html.parser')
        pagination = html.select('.pagination')

        for p in pagination:
            LastPage = p.select('a')[-2].get_text()

        AllChannels = []
        AllChannelsLinks = []
        for i in range(1, int(LastPage)+1):
            new_r= requests.get(f'https://channelcrawler.com/eng/results2/{Category}/page:{i}')
            new_html = BeautifulSoup(new_r.text, 'html.parser')
            channels = new_html.select('.channel')
            for channel in channels:
                title = channel.select('a')[0].get_text()
                link = channel.select('a')[0]['href']

influencer/templates/register/register copy.html
{% extends 'base/base.html' %}
{% block content %}


    <div class="container">
        
        <div class="row justify-content-center">
            <div class="col-md-8 mt-5">
                <div class="card">
                    <div class="card-header">Register</div>
    
                    <div class="card-body">
                        <form method="POST" action="">
                            {% csrf_token %}
    
                            <div class="form-group row mt-3">
                                <label for="username" class="col-md-4 col-form-label text-md-right">Username</label>
    
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="username" required>
                                </div>
                            </div>
    
                            <div class="form-group row mt-3">
                                <label for="email" class="col-md-4 col-form-label text-md-right">E-Mail Address</label>
    
                                <div class="col-md-6">
                                    <input  
                                            type="text" 
                                            name="email" 
                                            class="form-control"
                                            hx-post="{% url 'influencer:check-email' %}" 
                                            hx-target="#Msg" 
                                            hx-trigger="keyup delay:2s"
                                            required
                                    >
                                </div>

                                <div id="Msg"></div>
                                

                            </div>

                           
    
                            <div class="form-group row mt-3">
                                <label for="password1" class="col-md-4 col-form-label text-md-right">Password</label>
    
                                <div class="col-md-6">
                                    <input  type="password" class="form-control" name="password1" required >
    
                                </div>
                            </div>
    
                            <div class="form-group row mt-3">
                                <label for="password2" class="col-md-4 col-form-label text-md-right">Confirm Password</label>
                                <div class="col-md-6">
                                    <input type="password" class="form-control" name="password2" required >
    
                                </div>
                            </div> 
                            
                            <div class="form-group row mb-0  mt-3">
                                <div class="col-md-6 offset-md-4">
                                    <form method='POST' action='{% url 'influencer:influencer-register' %}'>
                                    <button type="submit" id="register_button" class="btn btn-primary">
                                        Register
                                    </button>
                                </form>
                                </div>
                            </div>    
                    </div>

    </div>

{% comment %} 
  <!-- JAVASCRIPT START FROM HERE -->
    <script>
        $(document).ready(function(){
            //class on change functionaolity
            // register start here
            $("#register_button").click(function (e) { 
            e.preventDefault();
                $.ajax({
                    url: "{% url 'influencer:influencer-register' %}",
                    type: "POST",
                    data: {
                        username:$("input[name='username']").val(),
                        
                        email:$("input[name='email']").val(),
                        otp:$("input[name='otp']").val(),
                        
                        password1:$("input[name='password1']").val(),
                        password2:$("input[name='password2']").val(),
                        
                        csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
                    },
                    console.log()
                    success: function (data) {
                        console.log(data);
                        console.log("data");
                        if(data.status == "success"){
                            window.location.href = "/";
                        }
                        else{
                            alert(data.status);
                        }
                    }
                });
    
    
            });
    
            // register end here
    
    
    
        });//main end
        </script>  {% endcomment %}



{% endblock content %}

influencer/templates/register/register.html
{% extends 'base/base.html' %}
{% block content %}


        
        <div class="form-login pt-5 pb-5 mt-5">
            <h2 class="text-center">Join as an Influencer</h2>
                <form method="POST"  class="row g-3 mt-3" action="">
                    {% csrf_token %}
                <div class="col-md-6">
                    <input type="text" class="form-control" name="username" placeholder='Enter a Full Name' required>
                </div>
                <div class="col-md-6">
                    <input  
                                            type="text" 
                                            name="email" 
                                            placeholder="Enter your Email"
                                            class="form-control"
                                            hx-post="{% url 'influencer:check-email' %}" 
                                            hx-target="#Msg" 
                                            hx-trigger="keyup delay:2s"
                                            required
                                    >

                  </div>
                  
                <div class="col-md-6">
                    <input  type="password" placeholder='Enter your Password' class="form-control" name="password1" required >
                </div>
                  <div class="col-md-6">
                    <input type="password" placeholder='Confirm Password'  class="form-control" name="password2" required >
                  </div>
                  <div id="Msg"></div>
                 
                <div class="col-12">
                  <button type="submit" class="btn btn-primary signup-btn">Create an Account</button>
                </div>
                <p class="text-center">Already have an account? <a href={% url 'influencer:login' %}>Login</a></p>
              </form>
            </div>
       

{% comment %} 
  <!-- JAVASCRIPT START FROM HERE -->
    <script>
        $(document).ready(function(){
            //class on change functionaolity
            // register start here
            $("#register_button").click(function (e) { 
            e.preventDefault();
                $.ajax({
                    url: "{% url 'influencer:influencer-register' %}",
                    type: "POST",
                    data: {
                        username:$("input[name='username']").val(),
                        
                        email:$("input[name='email']").val(),
                        otp:$("input[name='otp']").val(),
                        
                        password1:$("input[name='password1']").val(),
                        password2:$("input[name='password2']").val(),
                        
                        csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val()
                    },
                    console.log()
                    success: function (data) {
                        console.log(data);
                        console.log("data");
                        if(data.status == "success"){
                            window.location.href = "/";
                        }
                        else{
                            alert(data.status);
                        }
                    }
                });
    
    
            });
    
            // register end here
    
    
    
        });//main end
        </script>  {% endcomment %}



{% endblock content %}